### ISSUE TITLE
Compile error if makefile missing -ltr 

### ISSUE THREAD

**Issue by ASLeonard** [refresh-bio/agc#1]
Hi
I was having issues compiling agc using `make -f makefile.release agc` (to avoid the python binding), and ran into several errors about a missing reference to a clcok like below
```
stats.c:(.text+0x11c2): undefined reference to `clock_gettime'
 undefined reference to `clock_gettime'
in function `_mi_clock_now':
```

Adding `-lrt` to the CLINK line of the makefile fixed this and I was able to get the program running beautifully. My libc is old (2.17) but my gcc is newer (11.2) which may be the cause of the issue, but in case anyone else runs into this it does fix it.

Best,
Alex

**Comment by sebastiandeorowicz** [comment]
AGC 3.1 is ready. This should be fixed now.
