### ISSUE TITLE
Query Reference Sample Name

### ISSUE THREAD

**Issue by lynnjo** [refresh-bio/agc#12]
Is there a way to query AGC for the sample name that was used as the reference?  I can get all sample names with the "listset" command but I have a scenario where AGC is used in conjunction with other applications and I need to know what sample name was used as the reference when storing the compressed genomes.

**Comment by sebastiandeorowicz** [comment]
The feature will be added (also for older archives) in the forthcoming v.3.1. We need 1-2 weeks to complete.

**Comment by lynnjo** [comment]
Thank you !

**Comment by lynnjo** [comment]
Thank you very much for adding this functionality!


From: sebastiandeorowicz ***@***.***>
Date: Monday, March 18, 2024 at 4:15 PM
To: refresh-bio/agc ***@***.***>
Cc: Lynn Carol Johnson ***@***.***>, Author ***@***.***>
Subject: Re: [refresh-bio/agc] Query Reference Sample Name (Issue #12)

Closed #12<https://github.com/refresh-bio/agc/issues/12> as completed.
