### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by KamilSJaron** [refresh-bio/agc#2]
Hi, sounds like a cool tool. 

I tried to run the tool installed via conda on `Debian GNU/Linux 9 (stretch)`, but when I tried to compress the toy examples I always get `Illegal instruction`.

```
conda install -c bioconda agc
cd toy_ex
agc create ref.fa a.fa b.fa > toy_example.agc
Illegal instruction (core dumped)
```

I also did try to compile the software on my own, but we have too old gcc and it makes a mess with the `<filesystem>` library.

Finally, thanks for the effort of making genomes.. small!

**Comment by sebastiandeorowicz** [comment]
Hi,
Can you tell me what is your CPU? Probably the problem is with AVX extensions, but let's verify this.
Best,

**Comment by KamilSJaron** [comment]
That is likely the problem! I originally tried just if the program work on our frontend with Intel(R) Xeon(R) CPU L5640 (it is quite old server).

Now I tried again on compute nodes and although I have not checked yet the output and stuff, it is not dropping the core dump error!

**Comment by sebastiandeorowicz** [comment]
I'll prepare non-AVX binaries for the older CPUs. Let you know soon.

**Comment by sebastiandeorowicz** [comment]
It took some time, but precompiled non-AVX version is ready: https://github.com/refresh-bio/agc/releases/tag/v2.0
