### ISSUE TITLE
Add MAC arm build to bioconda

### ISSUE THREAD

**Issue by lynnjo** [refresh-bio/agc#21]
There was a previous issues requesting MAC M1/M2/M3 support.  That has been closed, and it looks like linux-aarch64 builds have been added but there is no build uploaded for MAC, perhaps because Bioconda did not support this.

 It looks like bioconda added MAC ARM support in July. Is it possible to upload an osx-arm AGC build to bioconda? Thanks

**Comment by sebastiandeorowicz** [comment]
Thank you for pointing support of MAC ARM by Bioconda. At the moment, I'm working on a new release of AGC with better speed and ratio (at least in some cases). I need a few weeks to complete. I think this will be an excellent moment to add osx-arm build to Bioconda.

**Comment by lynnjo** [comment]
Thanks @sebastiandeorowicz  - looking forward to the new release changes!

**Comment by sebastiandeorowicz** [comment]
AGC 3.1 for MAC ARM is in Bioconda. The recently released AGC 3.2 version will be available soon.
