### ISSUE TITLE
libraduls source?

### ISSUE THREAD

**Issue by Millak** [refresh-bio/agc#4]
Where does the raduls library come from? I didn't see it mentioned in the README or elsewhere in the repo so I was hoping you could point me where I can get the source for it.

**Comment by sebastiandeorowicz** [comment]
RADULS is our radix-sorter (https://github.com/refresh-bio/RADULS ). Nevertheless, in AGC we use its non-public variant (in-place radix sort). We plan to publish this variant in some time. Nevertheless, we have to work on it a bit.

**Comment by sebastiandeorowicz** [comment]
V.3.1, which should be ready in 1-2 weeks, will support M1/M2 CPUs as well as other ARM-based machines.
